# Common Features
USER_ID_FIELD: userId
ITEM_ID_FIELD: itemId
#RATING_FIELD: rating
TIME_FIELD: timestamp
# Selectively Loading
load_cols: [itemId, userId, timestamp]

# Filtering
max_user_inter_num: ~
min_user_inter_num: 5
max_item_inter_num: ~
min_item_inter_num: 5
field_separator: ","
